import json
import time
import hashlib
from web3 import Web3
from eth_account import Account

# ==========================================
# CONFIGURATION
# ==========================================
RPC_URL = "http://127.0.0.1:8545"  # Local Hardhat Node
CONTRACT_ADDRESS = "0x5FbDB2315678afecb367f032d93F642f64180aa3" # REPLACE WITH DEPLOYED ADDRESS
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Default Hardhat Account #0

# Load ABI (Ideally load this from the json file generated by Hardhat)
# For this script, I will include a minimal Interface ABI
CONTRACT_ABI = [
    {
        "inputs": [
            {"internalType": "bytes32", "name": "_docHash", "type": "bytes32"},
            {"internalType": "enum BankAuditLedger.ActionType", "name": "_actionType", "type": "uint8"},
            {"internalType": "string", "name": "_metadata", "type": "string"}
        ],
        "name": "recordAction",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "uint256", "name": "logId", "type": "uint256"},
            {"indexed": True, "internalType": "bytes32", "name": "documentHash", "type": "bytes32"},
            {"indexed": True, "internalType": "address", "name": "actor", "type": "address"},
            {"indexed": False, "internalType": "enum BankAuditLedger.ActionType", "name": "actionType", "type": "uint8"},
            {"indexed": False, "internalType": "uint256", "name": "timestamp", "type": "uint256"}
        ],
        "name": "LogCreated",
        "type": "event"
    }
]

class BlockchainLogger:
    """
    A Python wrapper to interact with the Solidity Audit Ledger.
    This runs inside the Bank's secure backend.
    """
    
    ACTION_MAP = {
        "UPLOAD": 0,
        "PII_MASKING": 1,
        "DATA_EXTRACTION": 2,
        "ADMIN_VIEW_RAW": 3,
        "DELETE": 4
    }

    def __init__(self):
        self.w3 = Web3(Web3.HTTPProvider(RPC_URL))
        if not self.w3.is_connected():
            raise Exception("❌ Blockchain Connection Failed. Is Hardhat Node running?")
        
        self.account = Account.from_key(PRIVATE_KEY)
        self.contract = self.w3.eth.contract(address=CONTRACT_ADDRESS, abi=CONTRACT_ABI)
        print(f"🔗 Connected to Blockchain Node. Actor: {self.account.address}")

    def generate_doc_hash(self, file_content: bytes) -> str:
        """Generates SHA-256 hash of a file to serve as its unique ID."""
        return "0x" + hashlib.sha256(file_content).hexdigest()

    def log_event(self, doc_bytes: bytes, action: str, metadata: str):
        """
        Writes an immutable log to the blockchain.
        """
        doc_hash = self.generate_doc_hash(doc_bytes)
        action_enum = self.ACTION_MAP.get(action, 0)
        
        print(f"📝 Preparing Transaction: {action} for Doc {doc_hash[:10]}...")

        # Build Transaction
        tx = self.contract.functions.recordAction(
            doc_hash,
            action_enum,
            metadata
        ).build_transaction({
            'from': self.account.address,
            'nonce': self.w3.eth.get_transaction_count(self.account.address),
            'gas': 2000000,
            'gasPrice': self.w3.eth.gas_price
        })

        # Sign Transaction
        signed_tx = self.w3.eth.account.sign_transaction(tx, PRIVATE_KEY)

        # Send Transaction
        tx_hash = self.w3.eth.send_raw_transaction(signed_tx.raw_transaction)
        
        print(f"🚀 Transaction Sent! Hash: {self.w3.to_hex(tx_hash)}")
        
        # Wait for receipt
        receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash)
        
        if receipt.status == 1:
            print(f"✅ Block Confirmed. Block Number: {receipt.blockNumber}")
            return self.w3.to_hex(tx_hash)
        else:
            print("❌ Transaction Failed!")
            return None

# ==========================================
# SIMULATION / MAIN EXECUTION
# ==========================================
if __name__ == "__main__":
    logger = BlockchainLogger()
    
    # Simulate a Bank Workflow
    dummy_pdf_content = b"Confidential Loan Application for John Doe..."
    
    # 1. Ingestion
    logger.log_event(dummy_pdf_content, "UPLOAD", "Source: Branch_Mumbai_04")
    
    # 2. AI Processing
    logger.log_event(dummy_pdf_content, "PII_MASKING", "Masked: Name, PAN, Phone")
    
    # 3. Emergency Access (Simulating an Admin check)
    print("\n⚠️  SIMULATING BREAK-GLASS EVENT...")
    logger.log_event(dummy_pdf_content, "ADMIN_VIEW_RAW", "Reason: Fraud Investigation Case #992")